export interface WikiItem {
  slug: string;
  title: string;
  category: string;
  excerpt: string;
  content: string;
}

export interface GameItem {
  slug: string;
  name: string;
  type: string;
  rarity: "Common" | "Uncommon" | "Rare" | "Epic" | "Legendary";
  description: string;
  stats?: Record<string, string | number>;
  usedIn?: string[];
  obtainedFrom?: string[];
}

export interface Creature {
  slug: string;
  name: string;
  type: "Passive" | "Aggressive" | "Boss" | "Mount";
  biome: string;
  description: string;
  drops?: string[];
  health?: number;
}

export interface Resource {
  slug: string;
  name: string;
  rarity: "Common" | "Uncommon" | "Rare" | "Epic" | "Legendary";
  biome: string;
  description: string;
  uses: string[];
}

export const gameItems: GameItem[] = [
  {
    slug: "fire-sword",
    name: "Fire Sword",
    type: "Weapon",
    rarity: "Rare",
    description: "A blade imbued with ember energy. Deals fire damage over time.",
    stats: { damage: 45, speed: 1.2, fireDamage: 12 },
    usedIn: ["Inferno Blade"],
    obtainedFrom: ["Volcanic Forge", "Dragon Drop"],
  },
  {
    slug: "iron-ore",
    name: "Iron Ore",
    type: "Material",
    rarity: "Common",
    description: "Raw iron used in basic crafting and forging.",
    usedIn: ["Iron Ingot", "Steel Bar", "Iron Sword"],
    obtainedFrom: ["Mountain Nodes", "Cave Deposits"],
  },
  {
    slug: "crystal-shard",
    name: "Crystal Shard",
    type: "Material",
    rarity: "Uncommon",
    description: "A glowing shard with latent magical properties.",
    usedIn: ["Mana Potion", "Crystal Staff", "Arcane Lens"],
    obtainedFrom: ["Crystal Caves", "Mage Drops"],
  },
  {
    slug: "dragon-scale",
    name: "Dragon Scale",
    type: "Material",
    rarity: "Epic",
    description: "A heat-resistant scale dropped by elder dragons.",
    stats: { armor: 30, fireResist: 50 },
    usedIn: ["Dragon Armor", "Fireproof Cloak"],
    obtainedFrom: ["Elder Dragon"],
  },
  {
    slug: "healing-potion",
    name: "Healing Potion",
    type: "Consumable",
    rarity: "Common",
    description: "Restores 100 HP over 5 seconds.",
    usedIn: ["Greater Healing Potion"],
    obtainedFrom: ["Alchemy Table", "Merchant"],
  },
  {
    slug: "arcane-staff",
    name: "Arcane Staff",
    type: "Weapon",
    rarity: "Epic",
    description: "Channels raw mana into devastating spells.",
    stats: { magicDamage: 80, manaRegen: 15 },
    usedIn: ["Staff of Ages"],
    obtainedFrom: ["Arcane Forge", "World Boss"],
  },
  {
    slug: "iron-sword",
    name: "Iron Sword",
    type: "Weapon",
    rarity: "Common",
    description: "A reliable starter weapon forged from iron ingots.",
    stats: { damage: 22, speed: 1.0 },
    usedIn: ["Steel Sword"],
    obtainedFrom: ["Anvil", "Blacksmith"],
  },
  {
    slug: "steel-sword",
    name: "Steel Sword",
    type: "Weapon",
    rarity: "Uncommon",
    description: "A stronger blade made from refined steel.",
    stats: { damage: 35, speed: 1.0 },
    usedIn: ["Enchanted Steel Sword"],
    obtainedFrom: ["Anvil"],
  },
  {
    slug: "leather-armor",
    name: "Leather Armor",
    type: "Armor",
    rarity: "Common",
    description: "Basic protection crafted from animal hides.",
    stats: { armor: 12, weight: 5 },
    usedIn: ["Reinforced Leather Armor"],
    obtainedFrom: ["Loom", "Crafting Bench"],
  },
  {
    slug: "dragon-armor",
    name: "Dragon Armor",
    type: "Armor",
    rarity: "Legendary",
    description: "Legendary armor forged from dragon scales and steel.",
    stats: { armor: 85, fireResist: 70, weight: 25 },
    usedIn: [],
    obtainedFrom: ["Forge", "Dragon Scale Crafting"],
  },
  {
    slug: "mana-potion",
    name: "Mana Potion",
    type: "Consumable",
    rarity: "Uncommon",
    description: "Restores 80 mana over 4 seconds.",
    usedIn: ["Greater Mana Potion"],
    obtainedFrom: ["Alchemy Table"],
  },
  {
    slug: "obsidian-dagger",
    name: "Obsidian Dagger",
    type: "Weapon",
    rarity: "Rare",
    description: "A razor-sharp dagger made from volcanic glass.",
    stats: { damage: 28, speed: 1.8, critChance: 15 },
    usedIn: ["Dual Obsidian Blades"],
    obtainedFrom: ["Volcanic Forge"],
  },
  {
    slug: "explorer-boat",
    name: "Explorer Boat",
    type: "Vehicle",
    rarity: "Uncommon",
    description: "A sturdy vessel for ocean exploration with moderate cargo space.",
    stats: { speed: 15, cargo: 20, durability: 500 },
    usedIn: ["Galleon"],
    obtainedFrom: ["Shipyard"],
  },
  {
    slug: "galleon",
    name: "Galleon",
    type: "Vehicle",
    rarity: "Epic",
    description: "A massive warship capable of crossing the deepest oceans.",
    stats: { speed: 20, cargo: 80, durability: 2000 },
    usedIn: [],
    obtainedFrom: ["Advanced Shipyard"],
  },
  {
    slug: "pickaxe",
    name: "Pickaxe",
    type: "Tool",
    rarity: "Common",
    description: "Essential tool for mining ore and breaking stone.",
    stats: { miningPower: 10, durability: 100 },
    usedIn: ["Steel Pickaxe"],
    obtainedFrom: ["Crafting Bench"],
  },
  {
    slug: "fishing-rod",
    name: "Fishing Rod",
    type: "Tool",
    rarity: "Common",
    description: "Used to catch fish and underwater treasures.",
    stats: { catchRate: 10, durability: 80 },
    usedIn: ["Reinforced Fishing Rod"],
    obtainedFrom: ["Crafting Bench"],
  },
  {
    slug: "torch",
    name: "Torch",
    type: "Tool",
    rarity: "Common",
    description: "Provides light in dark caves and nighttime exploration.",
    stats: { lightRadius: 8, burnTime: 300 },
    usedIn: ["Lantern"],
    obtainedFrom: ["Crafting Bench"],
  },
  {
    slug: "bow",
    name: "Wooden Bow",
    type: "Weapon",
    rarity: "Common",
    description: "A simple ranged weapon for hunting and combat.",
    stats: { damage: 18, speed: 0.8 },
    usedIn: ["Reinforced Bow"],
    obtainedFrom: ["Carpenter's Bench"],
  },
  {
    slug: "reinforced-bow",
    name: "Reinforced Bow",
    type: "Weapon",
    rarity: "Uncommon",
    description: "A sturdier bow with improved range and damage.",
    stats: { damage: 32, speed: 0.9, range: 40 },
    usedIn: ["Crystal Bow"],
    obtainedFrom: ["Carpenter's Bench"],
  },
  {
    slug: "shield",
    name: "Wooden Shield",
    type: "Armor",
    rarity: "Common",
    description: "Basic protection against melee and ranged attacks.",
    stats: { block: 15, durability: 150 },
    usedIn: ["Iron Shield"],
    obtainedFrom: ["Crafting Bench"],
  },
  {
    slug: "steel-pickaxe",
    name: "Steel Pickaxe",
    type: "Tool",
    rarity: "Uncommon",
    description: "A reinforced pickaxe for faster mining and better durability.",
    stats: { miningPower: 18, durability: 250 },
    usedIn: ["Diamond Pickaxe"],
    obtainedFrom: ["Anvil"],
  },
  {
    slug: "crystal-bow",
    name: "Crystal Bow",
    type: "Weapon",
    rarity: "Epic",
    description: "A bow strung with crystallized magic thread. Arrows pierce armor.",
    stats: { damage: 55, speed: 1.0, range: 60, magicDamage: 15 },
    usedIn: ["Ethereal Bow"],
    obtainedFrom: ["Arcane Forge"],
  },
  {
    slug: "longsword",
    name: "Longsword",
    type: "Weapon",
    rarity: "Uncommon",
    description: "A balanced blade with reach and cutting power.",
    stats: { damage: 38, speed: 1.0, range: 1.5 },
    usedIn: ["Knight's Longsword"],
    obtainedFrom: ["Anvil"],
  },
  {
    slug: "battle-axe",
    name: "Battle Axe",
    type: "Weapon",
    rarity: "Rare",
    description: "A heavy axe capable of cleaving through shields and armor.",
    stats: { damage: 52, speed: 0.7, cleave: 2 },
    usedIn: ["Dwarven Battle Axe"],
    obtainedFrom: ["Forge"],
  },
  {
    slug: "war-hammer",
    name: "War Hammer",
    type: "Weapon",
    rarity: "Rare",
    description: "A brutal crushing weapon that ignores partial armor.",
    stats: { damage: 48, speed: 0.6, armorPen: 25 },
    usedIn: ["Titan Hammer"],
    obtainedFrom: ["Forge"],
  },
  {
    slug: "crossbow",
    name: "Crossbow",
    type: "Weapon",
    rarity: "Uncommon",
    description: "A mechanical ranged weapon with high damage and slow reload.",
    stats: { damage: 45, speed: 0.4, range: 50 },
    usedIn: ["Heavy Crossbow"],
    obtainedFrom: ["Carpenter's Bench"],
  },
  {
    slug: "throwing-knives",
    name: "Throwing Knives",
    type: "Weapon",
    rarity: "Common",
    description: "Light blades for quick ranged attacks and stealth takedowns.",
    stats: { damage: 12, speed: 2.0, range: 15 },
    usedIn: ["Enchanted Throwing Knives"],
    obtainedFrom: ["Crafting Bench"],
  },
  {
    slug: "spear",
    name: "Spear",
    type: "Weapon",
    rarity: "Common",
    description: "A simple polearm with superior reach against melee foes.",
    stats: { damage: 28, speed: 0.9, range: 2.5 },
    usedIn: ["Pike"],
    obtainedFrom: ["Crafting Bench"],
  },
  {
    slug: "halberd",
    name: "Halberd",
    type: "Weapon",
    rarity: "Rare",
    description: "A versatile polearm combining axe blade and spear point.",
    stats: { damage: 44, speed: 0.8, range: 2.8, cleave: 1 },
    usedIn: ["Royal Halberd"],
    obtainedFrom: ["Forge"],
  },
  {
    slug: "mace",
    name: "Mace",
    type: "Weapon",
    rarity: "Common",
    description: "A spiked club effective against armored opponents.",
    stats: { damage: 30, speed: 0.9, armorPen: 10 },
    usedIn: ["Flanged Mace"],
    obtainedFrom: ["Anvil"],
  },
  {
    slug: "chainmail",
    name: "Chainmail Armor",
    type: "Armor",
    rarity: "Uncommon",
    description: "Flexible armor made of interlocking metal rings.",
    stats: { armor: 28, weight: 12, slashResist: 15 },
    usedIn: ["Reinforced Chainmail"],
    obtainedFrom: ["Anvil"],
  },
  {
    slug: "plate-armor",
    name: "Plate Armor",
    type: "Armor",
    rarity: "Rare",
    description: "Heavy solid plates offering maximum physical protection.",
    stats: { armor: 55, weight: 35, bluntResist: 20 },
    usedIn: ["Knight's Plate"],
    obtainedFrom: ["Forge"],
  },
  {
    slug: "mage-robe",
    name: "Mage Robe",
    type: "Armor",
    rarity: "Uncommon",
    description: "Light robes that enhance mana regeneration and magic power.",
    stats: { armor: 8, weight: 3, manaRegen: 25, magicBoost: 15 },
    usedIn: ["Archmage Robe"],
    obtainedFrom: ["Loom"],
  },
  {
    slug: "ranger-vest",
    name: "Ranger Vest",
    type: "Armor",
    rarity: "Uncommon",
    description: "Light armor for scouts and archers. Improves movement speed.",
    stats: { armor: 18, weight: 6, speedBoost: 10 },
    usedIn: ["Master Ranger Vest"],
    obtainedFrom: ["Loom"],
  },
  {
    slug: "iron-helmet",
    name: "Iron Helmet",
    type: "Armor",
    rarity: "Common",
    description: "Basic head protection forged from iron plates.",
    stats: { armor: 10, weight: 4 },
    usedIn: ["Steel Helmet"],
    obtainedFrom: ["Anvil"],
  },
  {
    slug: "leather-boots",
    name: "Leather Boots",
    type: "Armor",
    rarity: "Common",
    description: "Sturdy boots that reduce stamina drain while running.",
    stats: { armor: 5, weight: 2, staminaEfficiency: 10 },
    usedIn: ["Reinforced Leather Boots"],
    obtainedFrom: ["Loom"],
  },
  {
    slug: "gauntlets",
    name: "Iron Gauntlets",
    type: "Armor",
    rarity: "Uncommon",
    description: "Hand protection that improves grip strength and melee damage.",
    stats: { armor: 8, weight: 3, meleeBoost: 5 },
    usedIn: ["Steel Gauntlets"],
    obtainedFrom: ["Anvil"],
  },
  {
    slug: "stamina-potion",
    name: "Stamina Potion",
    type: "Consumable",
    rarity: "Common",
    description: "Restores 80 stamina over 4 seconds.",
    usedIn: ["Greater Stamina Potion"],
    obtainedFrom: ["Alchemy Table"],
  },
  {
    slug: "antidote",
    name: "Antidote",
    type: "Consumable",
    rarity: "Common",
    description: "Cures poison and venom effects instantly.",
    usedIn: ["Universal Antidote"],
    obtainedFrom: ["Alchemy Table"],
  },
  {
    slug: "bandage",
    name: "Bandage",
    type: "Consumable",
    rarity: "Common",
    description: "Stops bleeding and restores 25 HP over 5 seconds.",
    usedIn: ["Medkit"],
    obtainedFrom: ["Crafting Bench"],
  },
  {
    slug: "cooked-meat",
    name: "Cooked Meat",
    type: "Consumable",
    rarity: "Common",
    description: "Restores 60 HP and 20 stamina. A reliable meal.",
    usedIn: ["Stew"],
    obtainedFrom: ["Campfire"],
  },
  {
    slug: "elixir-of-speed",
    name: "Elixir of Speed",
    type: "Consumable",
    rarity: "Rare",
    description: "Temporarily increases movement and attack speed by 25%.",
    usedIn: ["Potion of Haste"],
    obtainedFrom: ["Alchemy Table"],
  },
  {
    slug: "steel-bar",
    name: "Steel Bar",
    type: "Material",
    rarity: "Common",
    description: "Refined steel for advanced weapons and tools.",
    usedIn: ["Steel Sword", "Steel Pickaxe", "Plate Armor"],
    obtainedFrom: ["Smelter"],
  },
  {
    slug: "leather-strip",
    name: "Leather Strip",
    type: "Material",
    rarity: "Common",
    description: "Treated leather strips for bindings and armor stitching.",
    usedIn: ["Leather Armor", "Bow String", "Saddle"],
    obtainedFrom: ["Tannery"],
  },
  {
    slug: "silk-thread",
    name: "Silk Thread",
    type: "Material",
    rarity: "Uncommon",
    description: "Fine thread used for magical garments and bowstrings.",
    usedIn: ["Mage Robe", "Crystal Bow", "Fishing Net"],
    obtainedFrom: ["Spider Nests", "Silk Farm"],
  },
  {
    slug: "diamond",
    name: "Diamond",
    type: "Material",
    rarity: "Epic",
    description: "An incredibly hard gemstone used for legendary gear.",
    stats: { value: 500 },
    usedIn: ["Diamond Pickaxe", "Legendary Jewelry"],
    obtainedFrom: ["Deep Cave Nodes"],
  },
  {
    slug: "ruby",
    name: "Ruby",
    type: "Material",
    rarity: "Rare",
    description: "A fiery red gem associated with strength and vitality.",
    stats: { value: 250 },
    usedIn: ["Fire Enchantment", "Ruby Ring"],
    obtainedFrom: ["Mountain Nodes", "Volcanic Caves"],
  },
  {
    slug: "sapphire",
    name: "Sapphire",
    type: "Material",
    rarity: "Rare",
    description: "A deep blue gem that channels cold and water magic.",
    stats: { value: 250 },
    usedIn: ["Ice Enchantment", "Sapphire Amulet"],
    obtainedFrom: ["Mountain Streams", "Ocean Depths"],
  },
  {
    slug: "emerald",
    name: "Emerald",
    type: "Material",
    rarity: "Rare",
    description: "A green gem linked to nature magic and growth.",
    stats: { value: 250 },
    usedIn: ["Nature Enchantment", "Emerald Circlet"],
    obtainedFrom: ["Forest Caves", "Ancient Ruins"],
  },
  {
    slug: "bronze-ingot",
    name: "Bronze Ingot",
    type: "Material",
    rarity: "Common",
    description: "An alloy of copper and tin for early metal tools.",
    usedIn: ["Bronze Sword", "Bronze Shield", "Statues"],
    obtainedFrom: ["Smelter"],
  },
  {
    slug: "cart",
    name: "Cart",
    type: "Vehicle",
    rarity: "Common",
    description: "A wheeled cart for transporting heavy loads over land.",
    stats: { speed: 8, cargo: 40, durability: 300 },
    usedIn: ["Wagon"],
    obtainedFrom: ["Carpenter's Bench"],
  },
  {
    slug: "lantern",
    name: "Lantern",
    type: "Tool",
    rarity: "Common",
    description: "A reusable light source fueled by oil or crystals.",
    stats: { lightRadius: 12, fuelDuration: 600 },
    usedIn: ["Magic Lantern"],
    obtainedFrom: ["Crafting Bench"],
  },
  {
    slug: "compass",
    name: "Compass",
    type: "Tool",
    rarity: "Uncommon",
    description: "Points toward the nearest discovered waypoint or base.",
    stats: { accuracy: 95 },
    usedIn: ["Explorer's Compass"],
    obtainedFrom: ["Crafting Bench"],
  },
  {
    slug: "rope",
    name: "Rope",
    type: "Tool",
    rarity: "Common",
    description: "Essential for climbing, binding, and crafting.",
    stats: { length: 20, strength: 100 },
    usedIn: ["Grappling Hook", "Bow", "Net"],
    obtainedFrom: ["Crafting Bench"],
  },
  {
    slug: "tent",
    name: "Tent",
    type: "Tool",
    rarity: "Common",
    description: "A portable shelter for resting while traveling.",
    stats: { comfort: 5, durability: 50 },
    usedIn: ["Large Tent"],
    obtainedFrom: ["Crafting Bench"],
  },
  {
    slug: "boomerang",
    name: "Boomerang",
    type: "Weapon",
    rarity: "Uncommon",
    description: "A curved throwing weapon that returns if it misses. Harder to master than it looks.",
    stats: { damage: 24, speed: 1.4, range: 20 },
    usedIn: ["Enchanted Boomerang"],
    obtainedFrom: ["Carpenter's Bench"],
  },
  {
    slug: "scythe",
    name: "Scythe",
    type: "Weapon",
    rarity: "Rare",
    description: "A farming tool turned brutal weapon. Wide swing arc catches three enemies at once.",
    stats: { damage: 36, speed: 0.8, range: 2.2, cleave: 3 },
    usedIn: ["Reaper's Scythe"],
    obtainedFrom: ["Forge"],
  },
  {
    slug: "grappling-hook",
    name: "Grappling Hook",
    type: "Tool",
    rarity: "Uncommon",
    description: "Fires a hooked line to cliff faces. Pulls you up fast, but costs stamina per use.",
    stats: { range: 25, durability: 80 },
    usedIn: ["Advanced Grappling Hook"],
    obtainedFrom: ["Crafting Bench"],
  },
  {
    slug: "bear-trap",
    name: "Bear Trap",
    type: "Tool",
    rarity: "Common",
    description: "Place on the ground to immobilize creatures or warn of incoming raids.",
    stats: { damage: 40, durability: 3 },
    usedIn: ["Spiked Trap"],
    obtainedFrom: ["Crafting Bench"],
  },
  {
    slug: "alchemist-flask",
    name: "Alchemist Flask",
    type: "Tool",
    rarity: "Common",
    description: "Required for mixing potions. Higher quality flasks reduce brewing failure chance.",
    stats: { quality: 10 },
    usedIn: ["Master Alchemist Flask"],
    obtainedFrom: ["Crafting Bench", "Merchant"],
  },
  {
    slug: "nightmare-helm",
    name: "Nightmare Helm",
    type: "Armor",
    rarity: "Legendary",
    description: "Forged from the skull of a slain world boss. Terrifies weak enemies on sight.",
    stats: { armor: 70, fearAura: 15, weight: 18 },
    usedIn: [],
    obtainedFrom: ["World Boss Crafting"],
  },
];

export const creatures: Creature[] = [
  {
    slug: "ancient-dragon",
    name: "Ancient Dragon",
    type: "Boss",
    biome: "Volcanic Fields",
    description: "A colossal dragon said to have shaped the world with its flames.",
    drops: ["Dragon Scale", "Dragon Heart", "Ember Gem"],
    health: 50000,
  },
  {
    slug: "forest-wolf",
    name: "Forest Wolf",
    type: "Aggressive",
    biome: "Woodlands",
    description: "Pack hunters that roam the deep forests.",
    drops: ["Wolf Pelt", "Raw Meat"],
    health: 320,
  },
  {
    slug: "highland-stag",
    name: "Highland Stag",
    type: "Passive",
    biome: "Highlands",
    description: "Majestic herbivores often hunted for their antlers.",
    drops: ["Stag Antler", "Raw Meat", "Leather"],
    health: 180,
  },
  {
    slug: "leviathan",
    name: "Leviathan",
    type: "Boss",
    biome: "Deep Ocean",
    description: "A sea serpent of mythic proportions.",
    drops: ["Leviathan Tooth", "Abyssal Pearl"],
    health: 75000,
  },
  {
    slug: "ember-whelp",
    name: "Ember Whelp",
    type: "Mount",
    biome: "Volcanic Fields",
    description: "A small dragon that can be tamed as a flying mount.",
    drops: ["Whelp Claw"],
    health: 800,
  },
  {
    slug: "cave-bear",
    name: "Cave Bear",
    type: "Aggressive",
    biome: "Caves",
    description: "Massive bears that hibernate in dark caverns.",
    drops: ["Bear Pelt", "Bear Claw"],
    health: 1200,
  },
  {
    slug: "storm-drake",
    name: "Storm Drake",
    type: "Mount",
    biome: "Highlands",
    description: "A lightning-infused drake that soars through thunderclouds.",
    drops: ["Storm Scale", "Drake Feather"],
    health: 2500,
  },
  {
    slug: "sea-serpent",
    name: "Sea Serpent",
    type: "Aggressive",
    biome: "Ocean",
    description: "Long serpents that attack ships from beneath the waves.",
    drops: ["Serpent Scale", "Venom Sac"],
    health: 2800,
  },
  {
    slug: "mountain-giant",
    name: "Mountain Giant",
    type: "Boss",
    biome: "Mountains",
    description: "Towering giants that hurl boulders at intruders.",
    drops: ["Giant's Heart", "Rune Stone"],
    health: 60000,
  },
  {
    slug: "forest-beast",
    name: "Forest Beast",
    type: "Aggressive",
    biome: "Forest",
    description: "Large predatory creatures that stalk the woodlands.",
    drops: ["Beast Fang", "Thick Hide"],
    health: 1500,
  },
  {
    slug: "snow-fox",
    name: "Snow Fox",
    type: "Passive",
    biome: "Snow",
    description: "Fluffy white foxes adapted to freezing temperatures.",
    drops: ["Snow Fox Pelt", "Raw Meat"],
    health: 60,
  },
  {
    slug: "swamp-toad",
    name: "Swamp Toad",
    type: "Passive",
    biome: "Swamp",
    description: "Giant toads that can be harvested for alchemical ingredients.",
    drops: ["Toad Oil", "Poison Gland"],
    health: 200,
  },
  {
    slug: "desert-scorpion",
    name: "Desert Scorpion",
    type: "Aggressive",
    biome: "Desert",
    description: "Venomous scorpions that burrow beneath the sand.",
    drops: ["Scorpion Tail", "Chitin"],
    health: 450,
  },
  {
    slug: "phoenix",
    name: "Phoenix",
    type: "Boss",
    biome: "Volcano",
    description: "A mythical bird of fire that resurrects upon death.",
    drops: ["Phoenix Feather", "Eternal Flame"],
    health: 45000,
  },
  {
    slug: "ocean-turtle",
    name: "Ocean Turtle",
    type: "Passive",
    biome: "Ocean",
    description: "Gentle turtles that carry small islands on their backs.",
    drops: ["Turtle Shell", "Pearl"],
    health: 3000,
  },
  {
    slug: "shadow-wolf",
    name: "Shadow Wolf",
    type: "Aggressive",
    biome: "Caves",
    description: "Nocturnal wolves with dark fur and glowing eyes.",
    drops: ["Shadow Pelt", "Moon Fang"],
    health: 500,
  },
  {
    slug: "griffin",
    name: "Griffin",
    type: "Mount",
    biome: "Mountains",
    description: "Majestic flying creatures that bond with brave riders.",
    drops: ["Griffin Feather", "Claw"],
    health: 3500,
  },
  {
    slug: "kraken",
    name: "Kraken",
    type: "Boss",
    biome: "Deep Ocean",
    description: "A massive squid-like monster that sinks entire fleets.",
    drops: ["Kraken Ink", "Tentacle", "Abyssal Eye"],
    health: 80000,
  },
  {
    slug: "deer",
    name: "Forest Deer",
    type: "Passive",
    biome: "Forest",
    description: "Common herbivores that provide meat and leather.",
    drops: ["Raw Meat", "Leather", "Deer Antler"],
    health: 120,
  },
  {
    slug: "rabbit",
    name: "Snow Rabbit",
    type: "Passive",
    biome: "Snow",
    description: "Small rabbits that can be caught for food or tamed as pets.",
    drops: ["Raw Meat", "Rabbit Pelt"],
    health: 30,
  },
  {
    slug: "frost-dragon",
    name: "Frost Dragon",
    type: "Boss",
    biome: "Snow Peaks",
    description: "An ancient wyrm whose breath freezes entire valleys solid.",
    drops: ["Frost Scale", "Dragon Heart", "Ice Crystal"],
    health: 52000,
  },
  {
    slug: "sand-wyrm",
    name: "Sand Wyrm",
    type: "Boss",
    biome: "Desert Dunes",
    description: "A colossal worm that burrows beneath the sand and devours travelers.",
    drops: ["Wyrm Tooth", "Desert Pearl", "Sand Gland"],
    health: 48000,
  },
  {
    slug: "ancient-golem",
    name: "Ancient Golem",
    type: "Boss",
    biome: "Ruins",
    description: "A stone construct animated by forgotten magic.",
    drops: ["Golem Core", "Rune Stone", "Ancient Gear"],
    health: 65000,
  },
  {
    slug: "volcanic-bat",
    name: "Volcanic Bat",
    type: "Aggressive",
    biome: "Volcano",
    description: "Fire-resistant bats that swarm intruders near lava flows.",
    drops: ["Bat Wing", "Ember Dust"],
    health: 180,
  },
  {
    slug: "river-crocodile",
    name: "River Crocodile",
    type: "Aggressive",
    biome: "River",
    description: "Ambush predators that lurk beneath murky water.",
    drops: ["Crocodile Hide", "Sharp Tooth"],
    health: 900,
  },
  {
    slug: "swamp-serpent",
    name: "Swamp Serpent",
    type: "Aggressive",
    biome: "Swamp",
    description: "Venomous snakes that strike from submerged vegetation.",
    drops: ["Serpent Venom", "Scale"],
    health: 400,
  },
  {
    slug: "cliff-lion",
    name: "Cliff Lion",
    type: "Aggressive",
    biome: "Mountains",
    description: "Agile predators that leap between rocky outcrops.",
    drops: ["Lion Pelt", "Claw"],
    health: 1400,
  },
  {
    slug: "dire-bear",
    name: "Dire Bear",
    type: "Aggressive",
    biome: "Forest",
    description: "Massive bears with reinforced bones and thick hide.",
    drops: ["Dire Bear Pelt", "Bear Heart"],
    health: 2800,
  },
  {
    slug: "phantom-stalker",
    name: "Phantom Stalker",
    type: "Aggressive",
    biome: "Caves",
    description: "Shadowy predators that blend into darkness.",
    drops: ["Shadow Essence", "Phantom Claw"],
    health: 700,
  },
  {
    slug: "venom-spider",
    name: "Venom Spider",
    type: "Aggressive",
    biome: "Caves",
    description: "Large spiders that spin webs across cave passages.",
    drops: ["Spider Silk", "Venom Sac"],
    health: 350,
  },
  {
    slug: "plague-rat",
    name: "Plague Rat",
    type: "Aggressive",
    biome: "Swamp",
    description: "Diseased rodents that spread poison through bites.",
    drops: ["Diseased Tail", "Plague Gland"],
    health: 80,
  },
  {
    slug: "thunder-hawk",
    name: "Thunder Hawk",
    type: "Aggressive",
    biome: "Highlands",
    description: "Electrified birds of prey that dive at high speed.",
    drops: ["Hawk Feather", "Storm Beak"],
    health: 600,
  },
  {
    slug: "coral-reef-shark",
    name: "Coral Reef Shark",
    type: "Aggressive",
    biome: "Ocean",
    description: "Sharks that patrol shallow reefs and shipwrecks.",
    drops: ["Shark Tooth", "Tough Hide"],
    health: 1600,
  },
  {
    slug: "plains-bison",
    name: "Plains Bison",
    type: "Passive",
    biome: "Plains",
    description: "Herd animals that graze across open grasslands.",
    drops: ["Bison Horn", "Thick Hide", "Raw Meat"],
    health: 800,
  },
  {
    slug: "meadow-horse",
    name: "Meadow Horse",
    type: "Passive",
    biome: "Meadows",
    description: "Swift horses that roam flowering meadows.",
    drops: ["Horse Mane", "Leather", "Raw Meat"],
    health: 500,
  },
  {
    slug: "river-fish",
    name: "River Fish",
    type: "Passive",
    biome: "River",
    description: "Common fish that swim upstream during spawning season.",
    drops: ["Raw Fish", "Fish Scale"],
    health: 20,
  },
  {
    slug: "glow-moth",
    name: "Glow Moth",
    type: "Passive",
    biome: "Caves",
    description: "Bioluminescent moths that illuminate dark caverns.",
    drops: ["Glow Dust", "Moth Wing"],
    health: 10,
  },
  {
    slug: "honey-bee",
    name: "Honey Bee",
    type: "Passive",
    biome: "Meadows",
    description: "Bees that produce honey in meadow hives.",
    drops: ["Honey", "Bee Wax", "Stinger"],
    health: 5,
  },
  {
    slug: "song-bird",
    name: "Song Bird",
    type: "Passive",
    biome: "Forest",
    description: "Colorful birds whose songs mark territory boundaries.",
    drops: ["Feather", "Small Beak"],
    health: 15,
  },
  {
    slug: "mountain-goat",
    name: "Mountain Goat",
    type: "Passive",
    biome: "Mountains",
    description: "Sure-footed goats that scale impossible cliffs.",
    drops: ["Goat Horn", "Leather", "Raw Meat"],
    health: 250,
  },
  {
    slug: "field-mouse",
    name: "Field Mouse",
    type: "Passive",
    biome: "Fields",
    description: "Tiny rodents that gather seeds and grains.",
    drops: ["Mouse Tail", "Grain"],
    health: 8,
  },
  {
    slug: "sand-strider",
    name: "Sand Strider",
    type: "Mount",
    biome: "Desert",
    description: "Tall lizards adapted to desert heat and sand traversal.",
    drops: ["Strider Scale", "Desert Claw"],
    health: 1800,
  },
  {
    slug: "frost-wolf",
    name: "Frost Wolf",
    type: "Mount",
    biome: "Snow",
    description: "Wolves bred for arctic travel and combat.",
    drops: ["Frost Pelt", "Ice Fang"],
    health: 2200,
  },
  {
    slug: "ocean-dolphin",
    name: "Ocean Dolphin",
    type: "Mount",
    biome: "Ocean",
    description: "Intelligent sea mammals that bond with coastal riders.",
    drops: ["Dolphin Fin", "Pearl"],
    health: 1500,
  },
  {
    slug: "moss-turtle",
    name: "Moss Turtle",
    type: "Passive",
    biome: "Swamp",
    description: "Slow turtles covered in medicinal moss.",
    drops: ["Turtle Shell", "Healing Moss"],
    health: 400,
  },
  {
    slug: "cave-salamander",
    name: "Cave Salamander",
    type: "Passive",
    biome: "Caves",
    description: "Amphibians that thrive in damp underground rivers.",
    drops: ["Salamander Tail", "Moist Skin"],
    health: 60,
  },
  {
    slug: "fire-beetle",
    name: "Fire Beetle",
    type: "Aggressive",
    biome: "Volcano",
    description: "Beetles with heated carapaces that scorch attackers.",
    drops: ["Fire Carapace", "Ember Gland"],
    health: 120,
  },
  {
    slug: "ice-golem",
    name: "Ice Golem",
    type: "Boss",
    biome: "Snow",
    description: "Animated ice that guards frozen treasure vaults.",
    drops: ["Ice Core", "Frozen Heart", "Rime Crystal"],
    health: 55000,
  },
  {
    slug: "shadow-panther",
    name: "Shadow Panther",
    type: "Aggressive",
    biome: "Forest",
    description: "Nocturnal cats that stalk prey in absolute silence.",
    drops: ["Shadow Pelt", "Panther Eye"],
    health: 1100,
  },
  {
    slug: "sky-whale",
    name: "Sky Whale",
    type: "Passive",
    biome: "Sky",
    description: "Leviathans that drift through high-altitude clouds.",
    drops: ["Cloud Blubber", "Sky Bone"],
    health: 10000,
  },
  {
    slug: "crystal-butterfly",
    name: "Crystal Butterfly",
    type: "Passive",
    biome: "Caves",
    description: "Butterflies with wings of living crystal.",
    drops: ["Crystal Wing", "Prism Dust"],
    health: 5,
  },
  {
    slug: "lava-snail",
    name: "Lava Snail",
    type: "Passive",
    biome: "Volcano",
    description: "Snails with magma-resistant shells.",
    drops: ["Magma Shell", "Lava Slime"],
    health: 40,
  },
  {
    slug: "reed-deer",
    name: "Reed Deer",
    type: "Passive",
    biome: "River",
    description: "Small deer that feed on riverside vegetation.",
    drops: ["Deer Antler", "Raw Meat", "Leather"],
    health: 140,
  },
  {
    slug: "stone-golem",
    name: "Stone Golem",
    type: "Boss",
    biome: "Mountains",
    description: "Animated rock formations that protect mountain passes.",
    drops: ["Stone Core", "Mountain Rune", "Golem Fist"],
    health: 58000,
  },
  {
    slug: "tidal-serpent",
    name: "Tidal Serpent",
    type: "Boss",
    biome: "Ocean",
    description: "A serpent that commands the tides and whirlpools.",
    drops: ["Tidal Scale", "Ocean Pearl", "Serpent Eye"],
    health: 72000,
  },
  {
    slug: "ash-wolf",
    name: "Ash Wolf",
    type: "Aggressive",
    biome: "Volcanic Fields",
    description: "Charred wolves that hunt in packs across cooling lava flows. Their bite causes burn wounds.",
    drops: ["Ash Pelt", "Burnt Fang", "Raw Meat"],
    health: 380,
  },
  {
    slug: "mist-stag",
    name: "Mist Stag",
    type: "Passive",
    biome: "Swamp",
    description: "Pale deer that appear during morning fog. Their antlers carry mild toxins.",
    drops: ["Mist Antler", "Raw Meat", "Leather"],
    health: 140,
  },
  {
    slug: "coral-golem",
    name: "Coral Golem",
    type: "Aggressive",
    biome: "Ocean",
    description: "Animated reef structures that defend their territory with crushing limbs.",
    drops: ["Living Coral", "Salt Crystal"],
    health: 1800,
  },
  {
    slug: "frost-owl",
    name: "Frost Owl",
    type: "Passive",
    biome: "Snow",
    description: "Silent hunters that dive at snow hares. Their feathers insulate against extreme cold.",
    drops: ["Owl Feather", "Raw Meat"],
    health: 45,
  },
  {
    slug: "dune-strider",
    name: "Dune Strider",
    type: "Mount",
    biome: "Desert",
    description: "Tall lizards that sprint across sand without sinking. Popular with desert nomads.",
    drops: ["Strider Hide", "Strider Meat"],
    health: 600,
  },
];

export const resources: Resource[] = [
  {
    slug: "iron",
    name: "Iron",
    rarity: "Common",
    biome: "Mountain",
    description: "Basic metal for weapons and tools.",
    uses: ["Weapon Crafting", "Armor", "Building"],
  },
  {
    slug: "crystal",
    name: "Crystal",
    rarity: "Uncommon",
    biome: "Cave",
    description: "Magic-infused crystals used in enchanting.",
    uses: ["Enchanting", "Staff Crafting", "Potions"],
  },
  {
    slug: "obsidian",
    name: "Obsidian",
    rarity: "Rare",
    biome: "Volcanic Fields",
    description: "Volcanic glass with sharp edges.",
    uses: ["Blade Crafting", "Arrowheads", "Decorations"],
  },
  {
    slug: "moonflower",
    name: "Moonflower",
    rarity: "Rare",
    biome: "Forest (Night)",
    description: "A luminescent flower that blooms under moonlight.",
    uses: ["Invisibility Potion", "Mana Regen", "Dyes"],
  },
  {
    slug: "abyssal-ore",
    name: "Abyssal Ore",
    rarity: "Legendary",
    biome: "Deep Ocean",
    description: "Metal forged in the depths of the ocean.",
    uses: ["Legendary Weapons", "Deep Diver Armor"],
  },
  {
    slug: "timber",
    name: "Timber",
    rarity: "Common",
    biome: "Forest",
    description: "Sturdy wood for construction and crafting.",
    uses: ["Building", "Bow Crafting", "Furniture"],
  },
  {
    slug: "coal",
    name: "Coal",
    rarity: "Common",
    biome: "Cave",
    description: "Burns hot and long. Essential for smelting.",
    uses: ["Smelting", "Forge Fuel", "Torch Crafting"],
  },
  {
    slug: "gold",
    name: "Gold",
    rarity: "Rare",
    biome: "Mountain",
    description: "Precious metal used for trading and high-end crafting.",
    uses: ["Trading", "Jewelry", "Decorative Armor"],
  },
  {
    slug: "silver",
    name: "Silver",
    rarity: "Uncommon",
    biome: "Mountain",
    description: "A shiny metal with anti-magic properties.",
    uses: ["Anti-Magic Items", "Jewelry", "Trading"],
  },
  {
    slug: "herbs",
    name: "Medicinal Herbs",
    rarity: "Common",
    biome: "Forest",
    description: "Common plants used in basic potion making.",
    uses: ["Healing Potions", "Antidotes", "Cooking"],
  },
  {
    slug: "sand",
    name: "Sand",
    rarity: "Common",
    biome: "Desert",
    description: "Fine grains used in glassmaking and construction.",
    uses: ["Glass Crafting", "Building", "Pottery"],
  },
  {
    slug: "salt",
    name: "Salt",
    rarity: "Common",
    biome: "Ocean",
    description: "Essential for preserving food and some alchemical recipes.",
    uses: ["Food Preservation", "Alchemy", "Trading"],
  },
  {
    slug: "leather",
    name: "Leather",
    rarity: "Common",
    biome: "Various",
    description: "Treated animal hide for armor and crafting.",
    uses: ["Armor Crafting", "Saddles", "Bags"],
  },
  {
    slug: "sulfur",
    name: "Sulfur",
    rarity: "Uncommon",
    biome: "Volcano",
    description: "Yellow mineral used in explosives and fire potions.",
    uses: ["Explosives", "Fire Potions", "Gunpowder"],
  },
  {
    slug: "ice-shard",
    name: "Ice Shard",
    rarity: "Rare",
    biome: "Snow",
    description: "Crystallized ice that never melts. Contains frost magic.",
    uses: ["Frost Weapons", "Cooling", "Ice Magic"],
  },
  {
    slug: "pearls",
    name: "Pearls",
    rarity: "Uncommon",
    biome: "Ocean",
    description: "Beautiful gems harvested from ocean creatures.",
    uses: ["Trading", "Jewelry", "Enchanting"],
  },
  {
    slug: "clay",
    name: "Clay",
    rarity: "Common",
    biome: "River",
    description: "Malleable earth used for pottery and brick-making.",
    uses: ["Pottery", "Bricks", "Dye Base"],
  },
  {
    slug: "flint",
    name: "Flint",
    rarity: "Common",
    biome: "Cave",
    description: "Hard stone that sparks when struck. Used for fire-starting and tools.",
    uses: ["Tool Crafting", "Fire Starting", "Arrowheads"],
  },
  {
    slug: "amber",
    name: "Amber",
    rarity: "Rare",
    biome: "Forest",
    description: "Fossilized tree resin containing ancient energy.",
    uses: ["Magic Amplification", "Jewelry", "Trading"],
  },
  {
    slug: "magma-stone",
    name: "Magma Stone",
    rarity: "Epic",
    biome: "Volcano",
    description: "A stone perpetually glowing with inner heat.",
    uses: ["Fire Enchanting", "Legendary Forge", "Heat Source"],
  },
  {
    slug: "stone",
    name: "Stone",
    rarity: "Common",
    biome: "Mountain",
    description: "Basic building material found everywhere.",
    uses: ["Building", "Tool Crafting", "Fortifications"],
  },
  {
    slug: "water",
    name: "Water",
    rarity: "Common",
    biome: "River",
    description: "Essential for survival, cooking, and farming.",
    uses: ["Cooking", "Farming", "Alchemy", "Brewing"],
  },
  {
    slug: "wheat",
    name: "Wheat",
    rarity: "Common",
    biome: "Fields",
    description: "A staple grain for bread and brewing.",
    uses: ["Bread", "Beer", "Animal Feed"],
  },
  {
    slug: "cotton",
    name: "Cotton",
    rarity: "Common",
    biome: "Fields",
    description: "Soft fibers for clothing and rope.",
    uses: ["Cloth", "Bandages", "Rope"],
  },
  {
    slug: "berries",
    name: "Berries",
    rarity: "Common",
    biome: "Forest",
    description: "Wild fruits that restore small amounts of health.",
    uses: ["Food", "Dyes", "Potions"],
  },
  {
    slug: "copper",
    name: "Copper",
    rarity: "Uncommon",
    biome: "Mountain",
    description: "A soft metal used for wiring and early tools.",
    uses: ["Bronze Alloy", "Wiring", "Decorations"],
  },
  {
    slug: "zinc",
    name: "Zinc",
    rarity: "Uncommon",
    biome: "Mountain",
    description: "Metal used in alloys and alchemical preparations.",
    uses: ["Brass Alloy", "Alchemy", "Batteries"],
  },
  {
    slug: "beeswax",
    name: "Beeswax",
    rarity: "Uncommon",
    biome: "Meadows",
    description: "Wax produced by bees for candles and sealing.",
    uses: ["Candles", "Polish", "Sealing Wax"],
  },
  {
    slug: "seaweed",
    name: "Seaweed",
    rarity: "Uncommon",
    biome: "Ocean",
    description: "Ocean vegetation rich in nutrients and binding agents.",
    uses: ["Food", "Fertilizer", "Potion Base"],
  },
  {
    slug: "mushrooms",
    name: "Mushrooms",
    rarity: "Uncommon",
    biome: "Forest",
    description: "Fungi with varied culinary and alchemical properties.",
    uses: ["Cooking", "Alchemy", "Dyes"],
  },
  {
    slug: "platinum",
    name: "Platinum",
    rarity: "Rare",
    biome: "Mountain",
    description: "A precious metal resistant to corrosion and magic.",
    uses: ["Legendary Jewelry", "Magic Resistance", "Trading"],
  },
  {
    slug: "jade",
    name: "Jade",
    rarity: "Rare",
    biome: "Mountains",
    description: "A green stone prized for carving and magical focus.",
    uses: ["Jewelry", "Magic Focus", "Trading"],
  },
  {
    slug: "coral",
    name: "Coral",
    rarity: "Rare",
    biome: "Ocean",
    description: "Marine structures with unique magical conductivity.",
    uses: ["Jewelry", "Water Magic", "Decorations"],
  },
  {
    slug: "nightshade",
    name: "Nightshade",
    rarity: "Rare",
    biome: "Swamp",
    description: "A toxic plant used in deadly poisons and antidotes.",
    uses: ["Poisons", "Antidotes", "Dark Magic"],
  },
  {
    slug: "dragon-bone",
    name: "Dragon Bone",
    rarity: "Rare",
    biome: "Volcano",
    description: "Remains of dragons, incredibly durable and magically charged.",
    uses: ["Legendary Weapons", "Necromancy", "Alchemy"],
  },
  {
    slug: "star-metal",
    name: "Star Metal",
    rarity: "Epic",
    biome: "Mountains",
    description: "Metal from fallen stars with cosmic energy.",
    uses: ["Cosmic Weapons", "Starmap Tools", "Legendary Armor"],
  },
  {
    slug: "philosopher-stone",
    name: "Philosopher Stone",
    rarity: "Epic",
    biome: "Caves",
    description: "A legendary alchemical catalyst capable of transmutation.",
    uses: ["Transmutation", "Immortality Elixir", "Legendary Crafting"],
  },
  {
    slug: "void-crystal",
    name: "Void Crystal",
    rarity: "Epic",
    biome: "Caves",
    description: "Crystals that absorb light and magic from surroundings.",
    uses: ["Void Magic", "Stealth Devices", "Anti-Magic Fields"],
  },
  {
    slug: "elder-wood",
    name: "Elder Wood",
    rarity: "Epic",
    biome: "Forest",
    description: "Wood from ancient trees with natural magical properties.",
    uses: ["Staves", "Wands", "Enchanted Furniture"],
  },
  {
    slug: "world-tree-sap",
    name: "World Tree Sap",
    rarity: "Legendary",
    biome: "Forest",
    description: "Sap from the mythical world tree. Grants immense vitality.",
    uses: ["Resurrection Potions", "Legendary Healing", "Immortality Elixir"],
  },
  {
    slug: "primordial-essence",
    name: "Primordial Essence",
    rarity: "Legendary",
    biome: "Deep Ocean",
    description: "Concentrated energy from the world's creation.",
    uses: ["Godlike Enchantments", "World-shaping", "Ascension"],
  },
  {
    slug: "titan-core",
    name: "Titan Core",
    rarity: "Legendary",
    biome: "Mountains",
    description: "The crystallized heart of an ancient titan.",
    uses: ["Titan Forging", "Golem Animation", "Legendary Armor"],
  },
  {
    slug: "granite",
    name: "Granite",
    rarity: "Common",
    biome: "Mountain",
    description: "Hard stone ideal for durable construction.",
    uses: ["Fortifications", "Statues", "Grindstones"],
  },
  {
    slug: "peat",
    name: "Peat",
    rarity: "Common",
    biome: "Swamp",
    description: "Compressed organic matter that burns slowly.",
    uses: ["Fuel", "Fertilizer", "Smoking Food"],
  },
  {
    slug: "bamboo",
    name: "Bamboo",
    rarity: "Common",
    biome: "Forest",
    description: "Fast-growing hollow stalks for lightweight construction.",
    uses: ["Building", "Furniture", "Scaffolding"],
  },
  {
    slug: "honey",
    name: "Honey",
    rarity: "Uncommon",
    biome: "Meadows",
    description: "Sweet nectar produced by bees. Natural preservative.",
    uses: ["Food", "Medicine", "Alchemy"],
  },
  {
    slug: "tar",
    name: "Tar",
    rarity: "Uncommon",
    biome: "Swamp",
    description: "Thick black liquid used for waterproofing and fuel.",
    uses: ["Waterproofing", "Ship Repair", "Torch Fuel"],
  },
  {
    slug: "mercury",
    name: "Mercury",
    rarity: "Rare",
    biome: "Caves",
    description: "Liquid metal with unique alchemical properties.",
    uses: ["Alchemy", "Mirrors", "Temperature Devices"],
  },
  {
    slug: "ebony",
    name: "Ebony",
    rarity: "Rare",
    biome: "Forest",
    description: "Dense black wood favored for weapons and instruments.",
    uses: ["Weapons", "Instruments", "Decorative Items"],
  },
  {
    slug: "meteorite-ore",
    name: "Meteorite Ore",
    rarity: "Epic",
    biome: "Various",
    description: "Metal from fallen meteors with otherworldly properties.",
    uses: ["Cosmic Weapons", "Meteor Forging", "Legendary Tools"],
  },
  {
    slug: "quicksilver",
    name: "Quicksilver",
    rarity: "Epic",
    biome: "Caves",
    description: "Enchanted mercury that moves against gravity.",
    uses: ["Enchanting", "Living Constructs", "Portals"],
  },
  {
    slug: "dragon-egg-fragment",
    name: "Dragon Egg Fragment",
    rarity: "Legendary",
    biome: "Volcano",
    description: "Shards of a dragon egg containing dormant life force.",
    uses: ["Dragon Summoning", "Life Magic", "Legendary Potions"],
  },
  {
    slug: "spirit-dust",
    name: "Spirit Dust",
    rarity: "Rare",
    biome: "Forest",
    description: "Powdered remains of forest spirits with animating power.",
    uses: ["Animation Magic", "Spirit Weapons", "Rituals"],
  },
  {
    slug: "volcanic-ash",
    name: "Volcanic Ash",
    rarity: "Common",
    biome: "Volcano",
    description: "Fine ash rich in minerals for fertilizer and ceramics.",
    uses: ["Fertilizer", "Ceramics", "Soap Making"],
  },
  {
    slug: "shell",
    name: "Shell",
    rarity: "Common",
    biome: "Ocean",
    description: "Hard casings from ocean creatures used for tools and trade.",
    uses: ["Tools", "Jewelry", "Trading", "Button Crafting"],
  },
  {
    slug: "quicksilver",
    name: "Quicksilver",
    rarity: "Rare",
    biome: "Caves",
    description: "Liquid metal found in deep veins. Essential for advanced alchemy and mirror crafting.",
    uses: ["Alchemy", "Mirrors", "Legendary Weapons"],
  },
  {
    slug: "moonpetal",
    name: "Moonpetal",
    rarity: "Epic",
    biome: "Forest",
    description: "Glowing white flowers that only bloom under full moons. Used in powerful healing salves.",
    uses: ["Healing Potions", "Elixirs", "Rare Dyes"],
  },
  {
    slug: "salt-crystal",
    name: "Salt Crystal",
    rarity: "Common",
    biome: "Ocean",
    description: "Compressed sea salt with preservation properties. Food cured with it lasts twice as long.",
    uses: ["Food Preservation", "Alchemy", "Trading"],
  },
  {
    slug: "volcanic-ash",
    name: "Volcanic Ash",
    rarity: "Common",
    biome: "Volcanic Fields",
    description: "Fine powder from recent eruptions. Mixed into clay to create heat-resistant ceramics.",
    uses: ["Ceramics", "Fertilizer", "Fire Resistance Potions"],
  },
  {
    slug: "frost-lichen",
    name: "Frost Lichen",
    rarity: "Uncommon",
    biome: "Snow",
    description: "Slow-growing crust that survives blizzards. Crushed into cold-weather gear treatments.",
    uses: ["Cold Resistance", "Dyes", "Alchemy"],
  },
  {
    slug: "sand-glass",
    name: "Sand Glass",
    rarity: "Common",
    biome: "Desert",
    description: "Purer than normal glass. Used for lenses and alchemical vials that won't crack under heat.",
    uses: ["Lenses", "Alchemy Vials", "Decorations"],
  },
];

export function searchAll(query: string) {
  const q = query.toLowerCase();
  return {
    items: gameItems.filter(
      (i) =>
        i.name.toLowerCase().includes(q) ||
        i.description.toLowerCase().includes(q) ||
        i.type.toLowerCase().includes(q)
    ),
    creatures: creatures.filter(
      (c) =>
        c.name.toLowerCase().includes(q) ||
        c.description.toLowerCase().includes(q) ||
        c.biome.toLowerCase().includes(q)
    ),
    resources: resources.filter(
      (r) =>
        r.name.toLowerCase().includes(q) ||
        r.description.toLowerCase().includes(q) ||
        r.biome.toLowerCase().includes(q)
    ),
  };
}

export function getRarityColor(rarity: string) {
  switch (rarity) {
    case "Common":
      return "text-zinc-400";
    case "Uncommon":
      return "text-green-400";
    case "Rare":
      return "text-blue-400";
    case "Epic":
      return "text-purple-400";
    case "Legendary":
      return "text-amber-400";
    default:
      return "text-muted-foreground";
  }
}
